ARG FROM_IMAGE_NAME

FROM ${FROM_IMAGE_NAME}

# get composer
RUN curl -OL https://getcomposer.org/download/1.5.2/composer.phar \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer

# install git
RUN apt-get update \
    && apt-get install -y git
# enable phpdebug

RUN apt-get install -y libxml2-dev \
    && docker-php-source extract \
    && cd /usr/src/php \
&& ./configure --enable-phpdbg